<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="TaskChat.Default" %>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <title>TaskChat</title>

    <!--script references -->
    <script src="Scripts/jquery-1.10.2.min.js"></script>
    <script src="Scripts/moment.min.js"></script>
    <script src="Scripts/handlebars-1.1.2.min.js"></script>
    <script src="Styles/js/bootstrap.min.js"></script>
    <script src="Scripts/jquery-ui-1.10.3.min.js"></script>
    <script src="Scripts/jquery.signalR-1.1.3.min.js"></script>


    <link type="text/css" rel="stylesheet" href="Styles/ChatStyle.css" />
    <link rel="stylesheet" href="/Styles/JQueryUI/themes/base/jquery.ui.all.css" />
    <link type="text/css" rel="stylesheet" href="Styles/css/bootstrap.min.css" />

    <!--Reference the autogenerated SignalR hub script. -->
    <script src="/signalr/hubs"></script>
    <script src="/Scripts/chat.js"></script>
    <script src="Scripts/taskrank.min.js"></script>
    <style>
        
    </style>

</head>
<body>
    <form id="mainForm" runat="server">
        <asp:ScriptManager ID="ScriptManager" EnablePageMethods="true" runat="server"></asp:ScriptManager>
    </form>

    <div class="navbar navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Trello Task Chat <i class="glyphicon glyphicon-list-alt"></i></a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>
    
    <div id="divContainer">

        <div id="divLogin" class="panel panel-default" style="width: 350px; margin-left: auto; margin-right: auto;">
            <div class="container panel-body">
                <form class="form-signin">
                    <h2 class="form-signin-heading">Sign In</h2>
                    <input id="txtNickName" type="text" class="form-control" placeholder="enter trello username" autofocus="" /><br />
                    <button id="btnGetBoards" class="btn btn-success btn-block" type="button" value="Get Boards">Get boards</button><br />
                    <div id="boardListOutput"></div>
                    <br />
                    <button id="btnStartChat" class="btn btn-primary btn-block" type="button" value="Start Chat">Sign in</button>
                </form>
            </div>
        </div>

        <%-- Handlebars template for displaying board drop down list --%>
        <script id="trelloBoards" type="text/html">
            <select id="boardSelect" class="form-control" name="boards">
                <option value="" selected="selected" disabled="disabled">select a board</option>
                {{#each board}}
                <option value="{{id}}">{{name}}</option>
                {{/each}}
            </select>
        </script>


        <div id="divChat">

            <div class="col-lg-3">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h3 class="panel-title">Update Card</h3>
                    </div>
                    <div class="panel-body">
                        <form>
                            <div class="form-group">
                                <label for="currentCardID">Card Id</label>
                                <input type="text" class="form-control" id="currentCardID" placeholder="current card id" readonly="true" />
                            </div>
                            <div class="form-group">
                                <label for="newCardLabel">Label</label>
                                <input type="text" class="form-control" id="newCardLabel" placeholder="enter new card info" />
                            </div>
                            <div class="form-group">
                                <label for="newCardDescription">Description</label>
                                <textarea rows="5" class="form-control" id="newCardDescription" placeholder="enter card description"></textarea>
                            </div>
                            <a id="updateCard" class="btn btn-primary">Update</a>
                        </form>

                    </div>
                </div>
            </div>


            <div class="col-lg-6">
                <div class="chatRoom panel panel-info">
                    <div class="panel-heading">
                        <h3 class="panel-title">Chat - welcome <span id='spanUser'></span></h3>

                    </div>


                    <div class="content">

                        <div id="divChatWindow" class="chatWindow">
                        </div>
                        <div id="divusers" class="users">
                            
                        </div>
                    </div>
                    <div style="width: 100%;">
                        <div class="input-group">
                            <input type="text" class="form-control" id="txtMessage" placeholder="enter message" />
                            <span class="input-group-btn">
                                <button id="btnSendMsg" value="Send" class="btn btn-primary" type="button" title="send">Send <i class="glyphicon glyphicon-send"></i></button>
                            </span>
                        </div>
                    </div>

                </div>
            </div>
            <input id="hdId" type="hidden" />
            <input id="hdUserName" type="hidden" />

            <div class="col-lg-3">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h3 class="panel-title">Cards</h3>
                    </div>
                    <div class="panel-body">

                        <div class="panel panel-primary">
                            <div class="panel-heading">
                                <h4 class="panel-title">Current Card</h4>
                            </div>

                            <div id="droppable" class="panel-body" style="height: auto;"></div>
                        </div>

                        <div id="cardListOutput"></div>

                        <%-- Handlebars template for displaying Trello cards --%>
                        <script id="trelloCards" type="text/html">
                            <%--<h4>Cards for: {{idBoard}}</h4>--%>
                            {{#each card}}
                            <div class="panel panel-default draggable">
                                <div class="panel-body" id="{{id}}">
                                    <h4 class="cardTitle">{{name}} </h4>
                                    {{#if due}}
                                    <span class="text-primary"><h5>due: {{formatDate due "short"}}</h5></span>
                                    {{/if}}
                                    <p class="cardDescription">{{desc}}</p>
                                    <a class="label label-success" href="{{shortUrl}}" target="_blank">open in trello</a>
                                </div>
                            </div>
                            {{/each}}
                        </script>

                    </div>
                </div>
            </div>
        </div>
    </div>

</body>

</html>

